PERMS_NAME_LOCALIZED = {
    # 一般伺服器權限
    "view_channel": "檢視頻道",
    "manage_channels": "管理頻道",
    "manage_roles": "管理身分組",
    "manage_emojis": "管理表情符號與貼圖",
    "view_audit_log": "檢視審核紀錄",
    "view_guild_insights": "檢視 Server Insights",
    "manage_webhooks": "管理 Webhooks",
    "manage_guild": "管理伺服器",
    # 會員權限
    "create_instant_invite": "建立邀請",
    "change_nickname": "更改暱稱",
    "manage_nicknames": "管理暱稱",
    "kick_members": "踢出成員",
    "ban_members": "對成員停權",
    # 文字頻道權限
    "send_messages": "傳送訊息及建立貼文",
    "send_messages_in_threads": "在討論串和貼文中傳送訊息",
    "create_public_threads": "建立公開討論串",
    "create_private_threads": "建立私人討論串",
    "embed_links": "嵌入連結",
    "attach_files": "附加檔案",
    "add_reactions": "新增反應",
    "external_emojis": "使用外部表情符號",
    "external_stickers": "使用外部貼圖",
    "mention_everyone": "提及 @everyone、@here 和所有身分組",
    "manage_messages": "管理訊息",
    "manage_threads": "管理討論串和貼文",
    "read_message_history": "讀取訊息歷史",
    "send_tts_messages": "傳送文字朗讀訊息",
    "use_application_commands": "使用應用程式命令",
    # 語音頻道權限
    "connect": "連接",
    "speak": "說話",
    "stream": "視訊通話",
    "use_embedded_activities": "使用活動",
    "use_voice_activation": "使用語音活動",
    "priority_speaker": "優先發言者",
    "mute_members": "將成員靜音",
    "deafen_members": "讓拒聽成員",
    "move_members": "移動成員",
    # 舞台頻道權限
    "request_to_speak": "請求發言",
    # 活動權限
    "manage_events": "管理活動",
    # 進階權限
    "administrator": "管理者",
    "moderate_members": "管理成員",
}