talent = {
    "ときのそら": "hololive/Tokino Sora.png",
    "ロボ子さん": "hololive/Robocosan.png",
    "AZKi": "hololive/AZKi.png",
    "さくらみこ": "hololive/Sakura Miko.png",
    "星街すいせい": "hololive/Hoshimachi Suisei.png",
    "夜空メル": "hololive/Yozora Mel.png",
    "アキ・ローゼンタール": "hololive/Aki Rosenthal.png",
    "赤井はあと": "hololive/Akai Haato.png",
    "白上フブキ": "hololive/Shirakami Fubuki.png",
    "夏色まつり": "hololive/Natsuiro Matsuri.png",
    "湊あくあ": "hololive/Minato Aqua.png",
    "紫咲シオン": "hololive/Murasaki Shion.png",
    "百鬼あやめ": "hololive/Nakiri Ayame.png",
    "癒月ちょこ": "hololive/Yuzuki Choco.png",
    "大空スバル": "hololive/Oozora Subaru.png",
    "大神ミオ": "hololive/Ookami Mio.png",
    "猫又おかゆ": "hololive/Nekomata Okayu.png",
    "戌神ころね": "hololive/Inugami Korone.png",
    "兎田ぺこら": "hololive/Usada Pekora.png",
    "不知火フレア": "hololive/Shiranui Flare.png",
    "白銀ノエル": "hololive/Shirogane Noel.png",
    "宝鐘マリン": "hololive/Houshou Marine.png",
    "天音かなた": "hololive/Amane Kanata.png",
    "角巻わため": "hololive/Tsunomaki Watame.png",
    "常闇トワ": "hololive/Tokoyami Towa.png",
    "姫森ルーナ": "hololive/Himemori Luna.png",
    "桐生ココ": "hololive/Kiryu Coco.png",
    "雪花ラミィ": "hololive/Yukihana Lamy.png",
    "桃鈴ねね": "hololive/Momosuzu Nene.png",
    "獅白ぼたん": "hololive/Shishiro Botan.png",
    "尾丸ポルカ": "hololive/Omaru Polka.png",
    "ラプラス・ダークネス": "hololive/La+ Darknesss.png",
    "鷹嶺ルイ": "hololive/Takane Lui.png",
    "博衣こより": "hololive/Hakui Koyori.png",
    "沙花叉クロヱ": "hololive/Sakamata Chloe.png",
    "風真いろは": "hololive/Kazama Iroha.png",
    "Mori Calliope": "hololive/Mori Calliope.png",
    "Takanashi Kiara": "hololive/Takanashi Kiara.png",
    "Ninomae Ina'nis": "hololive/Ninomae Ina'nis.png",
    "Gawr Gura": "hololive/Gawr Gura.png",
    "Watson Amelia": "hololive/Watson Amelia.png",
    "IRyS": "hololive/IRyS.png",
    "Ceres Fauna": "hololive/Ceres Fauna.png",
    "Ouro Kronii": "hololive/Ouro Kronii.png",
    "Nanashi Mumei": "hololive/Nanashi Mumei.png",
    "Hakos Baelz": "hololive/Hakos Baelz.png",
    "Tsukumo Sana": "hololive/Tsukumo Sana.png",
    "Shiori Novella": "hololive/Shiori Novella.png",
    "Koseki Bijou": "hololive/Koseki Bijou.png",
    "Nerissa Ravencroft": "hololive/Nerissa Ravencroft.png",
    "Fuwawa Abyssgard": "hololive/Fuwawa Abyssgard.png",
    "Mococo Abyssgard": "hololive/Mococo Abyssgard.png",
    "Ayunda Risu": "hololive/Ayunda Risu.png",
    "Moona Hoshinova": "hololive/Moona Hoshinova.png",
    "Airani Iofifteen": "hololive/Airani Iofifteen.png",
    "Kureiji Ollie": "hololive/Kureiji Ollie.png",
    "Anya Melfissa": "hololive/Anya Melfissa.png",
    "Pavolia Reine": "hololive/Pavolia Reine.png",
    "Vestia Zeta": "hololive/Vestia Zeta.png",
    "Kaela Kovalskia": "hololive/Kaela Kovalskia.png",
    "Kobo Kanaeru": "hololive/Kobo Kanaeru.png",
    "友人A（えーちゃん）": "hololive/Friend-A.png",
    "春先のどか": "hololive/Harusaki Nodoka.png",
    "火威青": "hololive/Hiodoshi Ao.png",
    "音乃瀬奏": "hololive/Otonose Kanade.png",
    "一条莉々華": "hololive/Ichijou Ririka.png",
    "儒烏風亭らでん": "hololive/Juufuutei Raden.png",
    "轟はじめ": "hololive/Todoroki Hajime.png",
}